package:
  name: hdf5
#  version: {{ environ['SIRF_VERSION'] }}
  version: 1.10.1


build:
  preserve_egg_dir: False
  number: 0
  missing_dso_whitelist:
    - $RPATH/libc.so.6  # [linux]
    - $RPATH/libm.so.6  # [linux]
    - $RPATH/libdl.so.2 # [linux]
    
requirements:
  build:
    - boost >=1.63
    - boost-cpp >=1.63
    - cmake >=3.1
    - vc 14 # [win and py36] 
    - vc 9  # [win and py27]
    - nose
    - coverage
    - fftw
      #    - swig >=3


  run:
          # - boost >=1.63
          # - boost-cpp >=1.63
          # - fftw
    - vc 14 # [win and py35]
    - vc 9  # [win and py27]
    - libstdcxx-ng # [unix]
    - libgcc-ng # [unix] 
	
about:
  home: http://www.ccppetmr.ac.uk
  license:  Apache 2.0 license
  summary: 'Synergistic Image Reconstruction Framework'
