package:
  name: gtest
#  version: {{ environ['SIRF_VERSION'] }}
  version: 1.8.0


build:
  preserve_egg_dir: False
#  number: 0
    
requirements:
  build:
    #- boost ==1.64.0	
    #- boost-cpp ==1.64.0 
    - boost >=1.63
    - boost-cpp >=1.63
#    - boost-cpp
#    - python 3.6 # [py36]
#    - python 2.7 # [py27]
    - cmake >=3.1
    - vc 14 # [win and py36] 
    - vc 9  # [win and py27]
#    - numpy
#    - scipy
#    - matplotlib
#    - docopt
    - h5py
#    - libxml2
    - psutil
    - nose
    - coverage
    - fftw
    - swig >=3
#    - libxslt
    - armadillo
    - ismrmrd


  run:
    - vc 14 # [win and py35]
    - vc 9  # [win and py27]
#    - python 3.6 # [py36]
#    - python 2.7 # [py27]
#    - numpy
#    - scipy
#    - matplotlib
#    - docopt
    - boost >=1.63
    - boost-cpp >=1.63
    - h5py
    - psutil
    - fftw
    - libgcc-ng
    - libstdcxx-ng
    - openblas
    - armadillo
    - ismrmrd
	
about:
  home: http://www.ccppetmr.ac.uk
  license:  Apache 2.0 license
  summary: 'Synergistic Image Reconstruction Framework'
