package:
  name: niftyreg
#  version: {{ environ['SIRF_VERSION'] }}
  version: 99d584e2b8ea0bffe7e65e40c8dc818751782d92


build:
  preserve_egg_dir: False
#  number: 0
  missing_dso_whitelist:
    - $RPATH/libc.so.6  # [linux]
    - $RPATH/libm.so.6  # [linux]
    - $RPATH/libdl.so.2 # [linux]
    - $RPATH/libpthread.so.0 # [linux]
    - $RPATH/librt.so.1 # [linux]
    - $RPATH/libicuuc.so.60  #[linux]
    - $RPATH/libicui18n.so.60 #[linux]
    
    
requirements:
  build:
    #- boost ==1.64.0	
    #- boost-cpp ==1.64.0 
    - boost >=1.63
#    - boost-cpp
#    - python 3.6 # [py36]
#    - python 2.7 # [py27]
    - cmake >=3.1
    - vc 14 # [win and py36] 
    - vc 9  # [win and py27]
#    - numpy
#    - scipy
#    - matplotlib
#    - docopt
#    - h5py
#    - libxml2
    - psutil
    - nose
    - coverage
#    - fftw
#    - swig >=3
#    - libxslt
#- armadillo
    - gtest
    - ismrmrd
    - _openmp_mutex # [linux]


  run:
    - _openmp_mutex # [linux]
    - vc 14 # [win and py35]
    - vc 9  # [win and py27]
#    - python 3.6 # [py36]
#    - python 2.7 # [py27]
#    - numpy
#    - scipy
#    - matplotlib
#    - docopt
#    - boost >=1.63
#    - psutil
#    - fftw
    - libgcc-ng
    - libstdcxx-ng
    - ismrmrd
    - _openmp_mutex # [linux]
      #    - openblas
    # - itk
	
about:
  home: http://www.ccppetmr.ac.uk
  license:  Apache 2.0 license
  summary: 'Synergistic Image Reconstruction Framework'
