version: '2.3'
services:
 sirf:
  image: synerbi/sirf:devel
  build:
   args:
    EXTRA_BUILD_FLAGS: "-DDEVEL_BUILD=ON -DBUILD_CIL=OFF"
   cache_from:
    - synerbi/sirf:core
    - synerbi/sirf:devel
