FROM ubuntu:16.04
LABEL \
  author.name="Casper da Costa-Luis"          \
  author.email=imaging@caspersci.uk.to        \
  maintainer.email=ccppetmr@stfc.ac.uk        \
  maintainer.url=https://www.ccppetmr.ac.uk/  \
  source.url=https://github.com/CCPPETMR/SIRF-SuperBuild/  \
  licence="MPLv2.0 (https://www.mozilla.org/en-GB/MPL/2.0/)"  \
  description="CCP PET-MR Ubuntu"

ENV DEBIAN_FRONTEND noninteractive

# Set locale, suppress warnings
RUN apt-get update && apt-get install -y apt-utils locales
RUN locale-gen en_GB.UTF-8
#ENV LC_ALL en_GB.UTF-8
ENV LANG en_GB.UTF-8
ENV LANGUAGE en_GB:en
#RUN localectl set-locale LANG="en_GB.UTF-8"

COPY build_essential-ubuntu.sh .
RUN bash build_essential-ubuntu.sh
RUN rm build_essential-ubuntu.sh

# Python (build)
COPY build_python-ubuntu.sh .
RUN bash build_python-ubuntu.sh
RUN rm build_python-ubuntu.sh

# Gadgetron
COPY build_gadgetron-ubuntu.sh .
RUN bash build_gadgetron-ubuntu.sh
RUN rm build_gadgetron-ubuntu.sh

# SIRF external deps
COPY build_system-ubuntu.sh .
RUN bash build_system-ubuntu.sh
RUN rm build_system-ubuntu.sh

# X11 forwarding
RUN apt-get update && apt-get install -y --no-install-recommends libx11-xcb1
RUN mkdir -p /usr/share/X11/xkb
RUN [ -e /usr/bin/X ] || ln -s /usr/bin/Xorg /usr/bin/X

ARG mainUser=sirfuser
ARG UID=1000
ARG GROUPS=1000
RUN addgroup --system --gid "$GROUPS" "$mainUser"
RUN adduser --home /home/"$mainUser" --shell /bin/bash --system --ingroup "$mainUser" --uid "$UID" "$mainUser"
#RUN echo "$mainUser:x:${uid}:${gid}:$mainUser,,,:/home/$mainUser:/bin/bash" >> /etc/passwd

RUN echo "$mainUser ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/"$mainUser"

ENV HOME /home/"$mainUser"
WORKDIR $HOME

COPY .bashrc .
COPY .profile .
RUN chown "$mainUser" .bashrc .profile
RUN chgrp "$mainUser" .bashrc .profile
RUN chmod 644 .bashrc .profile

RUN apt-get clean
USER "$mainUser"
ENV DEBIAN_FRONTEND ''

CMD cd $HOME && /bin/bash --init-file .profile
