services:
 foundation:
  image: synerbi/jupyter:foundation-gpu
  build:
   args:
    ROOT_IMAGE: nvidia/cuda:12.9.2-cudnn-devel-ubuntu24.04
    PYTHON_VERSION: 3.12
 base:
  image: synerbi/jupyter:base-gpu
 minimal:
  image: synerbi/jupyter:minimal-gpu
 scipy:
  image: synerbi/jupyter:scipy-gpu
 sirf-build:
  image: synerbi/jupyter:sirf-build-gpu
  build:
   target: build
   args:
    BUILD_GPU: 1
    Gadgetron_USE_CUDA: "ON"
 sirf:
  deploy: {resources: {reservations: {devices: [{driver: nvidia, count: all, capabilities: [gpu]}]}}}
  image: synerbi/sirf:latest-gpu
  build:
   target: sirf
   args:
    BUILD_GPU: 1
    Gadgetron_USE_CUDA: "ON"
   cache_from: [synerbi/jupyter:sirf-build-gpu]
