# list items (with a comment containing "GPU") are auto-uncommented in docker GPU builds
name: base
channels:
  # - nvidia # (GPU)
  - https://software.repos.intel.com/python/conda # cil
  # - https://tomography.stfc.ac.uk/conda # cil
  - ccpi  # cil
  - conda-forge
  - defaults
dependencies:
  - setuptools
  - wheel
  - swig >=4.2
  - pytest
  - pytest-cov
  - scipy
  - docopt
  - matplotlib
  - pandas
  - tifffile
  - nibabel
  - deprecation
  - nose
  - zenodo_get
  - jupytext
  - tensorboard
  - tensorboardx
  - llvm-openmp
  - jupyterlab_widgets
  - ipywidgets >=8
  - ipympl
  # - ccpi::tigre >=3.1.3  # cil (GPU)
  # - astra-toolbox::astra-toolbox 2  # cil (GPU)
  # - cuda-version 12.9.*  # cil (GPU)
  - ipp =2021.12           # cil
  - ipp-devel =2021.12     # cil
  - ipp-include =2021.12   # cil
  - ccpi-regulariser >=25  # cil
  - cil-data >=22          # cil
  - httomo::tomophantom >=3.1.4 # cil
  - ccpi::dxchange >=0.2.1 # cil
  - h5py           # cil
  - numba          # cil
  - numpy >=2      # cil
  - olefile >=0.46 # cil
  - pillow         # cil
  - pywavelets     # cil
  - tqdm           # cil
  - pip
  - pip:
    - git+https://github.com/ismrmrd/ismrmrd-python-tools.git@master#egg=ismrmrd-python-tools
    - unittest-parametrize # cil
