package:
  name: sirf
#  version: {{ environ['SIRF_VERSION'] }}
  version: 2.1.0


build:
  preserve_egg_dir: False
  number: 0
  missing_dso_whitelist:
    - $RPATH/libc.so.6  # [linux]
    - $RPATH/libm.so.6  # [linux]
    - $RPATH/libdl.so.2 # [linux]
    - $RPATH/libpthread.so.0 # [linux]
    - $RPATH/librt.so.1 # [linux]
    - $RPATH/libicuuc.so.60  #[linux]
    - $RPATH/libicui18n.so.60 #[linux]
    
    
requirements:
  build:
    #- boost ==1.64.0	
    #- boost-cpp ==1.64.0 
    - boost >=1.63
#    - boost-cpp
    - python 
    - {{ pin_compatible('numpy', max_pin='x.x') }}
#    - python 2.7 # [py27]
    - cmake >=3.1
    - vc 14 # [win and py36] 
    - vc 9  # [win and py27]
#    - scipy
#    - matplotlib
#    - docopt
    - h5py
    - hdf5 ==1.10.1
#    - libxml2
    - psutil
    - nose
    - coverage
    - fftw
    - swig >=3
#    - libxslt
#    - armadillo
    - gtest
    - ismrmrd


  run:
    - vc 14 # [win and py35]
    - vc 9  # [win and py27]
    - python
    - {{ pin_compatible('numpy', max_pin='x.x') }}
    - scipy
    - matplotlib
    - docopt
    - gadgetron ==b6191eaaa72ccca6c6a5fe4c0fa3319694f512ab
    - h5py
    # - stir
    # - niftyreg
#    - boost >=1.63
#    - h5py
#    - psutil
#    - fftw
#    - libgcc-ng
#    - libstdcxx-ng
#    - openblas
#    - armadillo
#    - gtest
#    - ismrmrd
    - libgcc-ng
    - libstdcxx-ng
    - ismrmrd
    - _openmp_mutex # [linux]
    - stir
	
about:
  home: http://www.ccppetmr.ac.uk
  license:  Apache 2.0 license
  summary: 'Synergistic Image Reconstruction Framework'
