name: Docker build service-gpu and core-gpu

on:
  pull_request:
    branches: [ master_test ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install docker and pre-reqs
        shell: bash -l {0}
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install ca-certificates curl gnupg lsb-release -y
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin
          sudo docker run hello-world

      
      - name: Build docker core-gpu image
        # Builds docker image from Docker file.
        shell: bash -l {0}
        run: |
          docker-compose -f docker/docker-compose.yml -f docker/docker-compose.srv-gpu.yml pull core
          docker-compose -f docker/docker-compose.yml -f docker/docker-compose.srv-gpu.yml build sirf

      
      - name: Build docker service-gpu image
        # Builds docker image from Docker file.
        shell: bash -l {0}
        run: |
          docker-compose -f docker/docker-compose.yml -f docker/docker-compose.srv.yml -f docker/docker-compose.srv-gpu.yml pull core
          docker-compose -f docker/docker-compose.yml -f docker/docker-compose.srv.yml -f docker/docker-compose.srv-gpu.yml build sirf
          
      - name: List images
        shell: bash -l {0}
        run: |
          docker image list
    # TODO: publish to come later
    # TODO: use matrix for tag names, yml names, etc.
